### ISSUE TITLE
Issues running tests via learn/rspec

### ISSUE THREAD

**Issue by Rygel-XVI** [learn-co-students/my_all-v-000#1034]
On Cloud9 when running the learn command it would get stuck so I would have to ctrl-c out of it. The errors I received were as follows. This occurred when I commented out the code as well so there were no syntax issues.

// ♥ learn
^C/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/resolver/api_specification.rb:8:in `<top (required)>': Interrupt
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:122:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:122:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:342:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:122:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:122:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:397:in `resolve_current'
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:245:in `finish_resolve'
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:313:in `block in activate_bin_path'
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:311:in `synchronize'
        from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:311:in `activate_bin_path'
        from /usr/local/rvm/gems/ruby-2.3.3/bin/learn-test:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

I ended up playing with it in my local ubuntu environment on atom and got different errors when I ran the tests:
![image](https://user-images.githubusercontent.com/20288765/33305282-3e043e78-d3c2-11e7-9bd2-56b36b37403a.png)

I ended up figuring out that if I commented out the 
# require 'pry'
at the top of the my_all.rb that I could run the tests via 'rspec' but running them via 'learn' was still broken.

I don't know if it is a me issue or a lab issue let me know if there is any other information you need I can probably replicate the issue.

**Comment by Rygel-XVI** [comment]
Spontaneously started working again later. Most likely an obscure issue with internet.
